dist: trusty
sudo: false
install:
  - composer install
  - cd theme; npm install
script:
  - exit 0
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: production
